from .CR1.animatedArmor import *
from .CR1.brassDragonWyrmling import *
from .CR1.brownBear import *
from .CR1.evilMage import *
from .CR1.ghoul import *
from .CR1.moorbounder import *
from .CR1.ogrillon import *
from .CR1.quickling import *
from .CR2.allosaurus import *
from .CR2.blackDragonWyrmling import *
from .CR2.carrionCrawler import *
from .CR2.ettercap import *
from .CR2.gargoyle import *
from .CR2.giantBoar import *
from .CR2.ogre import *
from .CR2.polarBear import *
from .CR2.sharkbodyAbomination import *
from .CR2.spinedDevil import *
from .flyingSnake import *